apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: { app: nginx-sample }
  template:
    metadata:
      labels: { app: nginx-sample }
    spec:
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 6 }}
      containers:
      - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports: [{containerPort: 80}]
