image:
  repository: harbor.local/demo/nginx-sample   # ← 필요시 본인 환경으로 수정
  tag: "0.0.1"         # Jenkins가 여기 값을 커밋으로 갱신하게 됨
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx        # ingress-nginx 사용 가정
  hosts:
    - host: demo.local    # 테스트 호스트명(나중에 /etc/hosts에 매핑)
      paths:
        - path: /
          pathType: Prefix
